---
title: "Visual Inspection: Research Entry Point"
top-level-division: section
jupyter: python3
bibliography:
  - ../references.bib
#nocite: |
#  @*
csl: ieee.csl
filters:
  - citetools
format:
  gfm:
    citeproc: false
    toc: true
    toc-depth: 6
    number-sections: true
title-block-banner: true
title-block-banner-color: "#ffddff"
---


```{python}
#| echo: false

# This cell is used to define a function that lets us run code and output the result as markdown, BEFORE it is rendered by Quarto.
from IPython.display import display, Markdown
dm = lambda s: display(Markdown(f'{s}'.strip()))
```


```{python}
#| echo: false

import datetime 
now = datetime.datetime.now()

dm(f'''
This document was rendered {now.strftime('%Y/%m/%d at %H:%M:%S')}.
''')
```


# About

The purpose of this document is supposed to be a kind of one-page Wiki.
It shall serve as the **entry-point** for people joining the project, as well as a **reference** for what is going on in the project (e.g., what approaches we are working on).


**\*Do not\* directly edit the file `readme.md` as your changes would be <u>lost</u>!**

Instead, use [**`Quarto`**](https://quarto.org/) to render this file ([`readme.`**`qmd`**](./readme.qmd)) to markdown like this:

```script
quarto render readme.qmd --to gfm
```

This will properly render and format the references (which can be found in [`../references.bib`](../references.bib)).
If you have not installed the extension **`citetools`**, do so:

```script
quarto install extension bcdavasconcelos/citetools
```


# Directory

Here is a directory of approaches that we either attempted, plan to attempt, or are just listed as food-for-thought.


- **`General`**
  - Data Pre-processing and -Augmentation
    - Image Segmentation
      - Papers:
        - [@kirillov2023sam]: [@kirillov2023sam]{.title-year}
      - Repositories:
        - [*Grounded-Segment-Anything*](https://github.com/IDEA-Research/Grounded-Segment-Anything); also look for "SAM" by Meta and at Huggingface. There are also freely available datasets.
    - Defect Localization
    - Data Augmentation
      - Gaussian Splats
        - Papers:
          - [@kerbl2023gauss]: [@kerbl2023gauss]{.title-year}
        - Repos:
          - [*3D Gaussian Splatting for Real-Time Radiance Field Rendering*](https://github.com/graphdeco-inria/gaussian-splatting)
  - Related Problems
    - Predictive Maintenance / Anomaly Detection
      - Papers:
        - [@huang2023uncertainty]: [@huang2023uncertainty]{.title-year}
        - [@nalisnick2019know]: [@nalisnick2019know]{.title-year}
    - Transfer Learning
      - Papers:
        - [@azari2023pred]: [@azari2023pred]{.title-year}
      - Links:
        - [*A Gentle Introduction to Transfer Learning for Deep Learning*](https://machinelearningmastery.com/transfer-learning-for-deep-learning/)
        - [*Transfer Learning in Keras with Computer Vision Models*](https://machinelearningmastery.com/how-to-use-transfer-learning-when-developing-convolutional-neural-network-models/)
- **`Supervised Learning`**
  - Papers:
    - [@neven2021unet]: [@neven2021unet]{.title-year}
    - [@ronneberger2015unet]: [@ronneberger2015unet]{.title-year}
    - [@cha2022unet]: [@cha2022unet]{.title-year}
    - [@yang2021automatic]: [@yang2021automatic]{.title-year}
- **`Semi-supervised Learning`**
  - Domain Generalization
    - Papers:
      - [@zhou2023dg]: [@zhou2023dg]{.title-year}
      - [@wang2023generalizing]: [@wang2023generalizing]{.title-year}
  - Domain Adaptation
    - Zero-Shot Learning
      - Papers:
        - [@chang2008dataless]: [@chang2008dataless]{.title-year}
        - [@larochelle2008zerodata]: [@larochelle2008zerodata]{.title-year}
        - [@jeong2023winclip]: [@jeong2023winclip]{.title-year}
        - [@deng2023anovl]: [@deng2023anovl]{.title-year}
      - Repositories:
        - [*Official Implementation of AnoVL (Updating)*](https://github.com/hq-deng/AnoVL)

- **`Unsupervised Learning`**
  - Normalizing Flows
    - Papers:
      - [@esteban2010density]: [@esteban2010density]{.title-year}
      - [@tabak2013family]: [@tabak2013family]{.title-year}
      - [@kingma2018glow]: [@kingma2018glow]{.title-year}
      - [@viberg2023]: [@viberg2023]{.title-year}
      - [@rudolph2022csf]: [@rudolph2022csf]{.title-year}
      - [@rudolph2021samesame]: [@rudolph2021samesame]{.title-year}
      - [@papamakarios2021normalizing]: [@papamakarios2021normalizing]{.title-year}
      - [@papamakarios2019phd]: [@papamakarios2019phd]{.title-year}
    - Repositories:
      - [*DifferNet: Semi-Supervised Defect Detection with Normalizing Flows*](https://github.com/marco-rudolph/differnet)
      - [*CS-Flow: Fully Convolutional Cross-Scale-Flows for Image-based Defect Detection*](https://github.com/marco-rudolph/cs-flow)
- **`Other`**
  - Potentially Interesting Concepts (Limited Applicability)
    - Cross-Modality
    - Typicality / Out-Of-Distribution Detection (OOD)
      - Papers:
        - [@nalisnick2019detecting]: [@nalisnick2019detecting]{.title-year}
        - [@caterini2021entropic]: [@caterini2021entropic]{.title-year}
        - [@zhang2023kld_ood]: [@zhang2023kld_ood]{.title-year}
        - [@osada2023ood_typicality]: [@osada2023ood_typicality]{.title-year}
  - Foundational Concepts
    - RNN Encoder--Decoder / Statistical Machine Translation
      - Papers:
        - [@cho2014rnnencdec]: [@cho2014rnnencdec]{.title-year}
        - [@sutskever2014seq2seq]: [@sutskever2014seq2seq]{.title-year}
      



# References {-}
